---
date: "`r Sys.Date()`"
author: Author Name
title: "RMarkdown Template"
output: 
  bookdown::html_document2:
    theme: "lumen"
    code_download: true
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    df_print: paged
knit: (function(inputFile, encoding) { 
  rmarkdown::render(inputFile, 
  encoding = encoding, 
  output_format = "html_document", 
  output_dir = here::here("output")) 
  })
editor_options:
  chunk_output_type: console
---

<!-- For equations: \begin{equation} \end{equation} and then add (\#eq:XXX) just before the end -->
  
# Set-up
  
```{r, echo=FALSE}
knitr::opts_chunk$set(comment = NA, echo = TRUE, eval = TRUE, 
                      warning = FALSE, message = FALSE, 
                      fig.width = 6, fig.height = 4)
```

# Libraries

```{r, message = FALSE}
# core libraries
library(conflicted)
library(tidyverse)
library(here)
# # analysis libraries
# library(gets)
# 
# # plotting libraries
# library(extrafont)
# library(viridis)
# library(cowplot)

rm(list=ls())
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("here", "here")
conflict_prefer("as.zoo.data.frame", "zoo")
```

# Data


# Analysis

```{r}
print(1:2000)
```


# References