---
date: '`r format(Sys.time(), "%B %d, %Y")`'
author:
  - name: Moritz Schwarz
    email: moritz.schwarz@ouce.ox.ac.uk
    institute: [ce, smith, inet]
  #   correspondence: true
  # - name: Christopher
  #   institute: ce
  # - name: Seaghán Mhartain
  #   institute: smith
  # - name: Rita Yuri Ynoue
  #   institute: inet
institute:
  - ce: Climate Econometrics, Nuffield College, University of Oxford
  - inet: Institute for New Economic Thinking at the Oxford Martin School
  - smith: Smith School of Enterprise and the Environment, University of Oxford
title: "RMarkdown Template"
bibliography: "`r rbbt::bbt_write_bib('biblio.bib', overwrite = TRUE)`"
output: 
  officedown::rdocx_document:
    reference_docx: StylesTemplate.docx
    toc: no
    toc_depth: 2
    mapstyles:
      Normal: ['First Paragraph']
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
  pdf_document:
    number_sections: yes
    toc: no
    toc_depth: 2
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
    header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={},
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
  bookdown::html_document2:
    theme: "lumen"
    code_download: true
    toc: true
    toc_float: true
    toc_depth: 2
    number_sections: true
    df_print: paged
    self_contained: FALSE # needed if the footer includes icons
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
    includes:
      after_body: footer.html
csl: nature.csl
urlcolor: blue
knit: (function(inputFile, encoding) { 
  encoding = encoding, 
  output_format = "all", 
  })
  rmarkdown::render(inputFile, 
  output_dir = here::here("output")) 
editor_options:
  chunk_output_type: console
---

<!-- For equations: \begin{equation} \end{equation} and then add (\#eq:XXX) just before the end -->


# Set-up

```{r, echo=FALSE}
knitr::opts_chunk$set(comment = NA, echo = TRUE, eval = TRUE, warning = FALSE, message = FALSE, 
                      fig.width = 6, fig.height = 4, fig.cap = TRUE)
```

`r if(!knitr:::is_html_output()){knitr::asis_output("# Table of Contents")}`

```{r toc, echo=FALSE} 
if (!knitr:::is_html_output()) {
  devtools::source_gist("c83e078bf8c81b035e32c3fc0cf04ee8", 
                      filename = 'render_toc.R')
render_toc(filename = knitr::current_input(), toc_header_name = "Table of Contents")
} 
```


# Libraries

```{r, eval=FALSE}
# core libraries
library(conflicted)
library(tidyverse)
library(here)

# # analysis libraries
# library(gets)
# 
# # plotting libraries
# library(extrafont)
# library(viridis)
# library(cowplot)

rm(list=ls())
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("lag", "dplyr")
conflict_prefer("here", "here")
conflict_prefer("as.zoo.data.frame", "zoo")
```

# Data


# Analysis


# References

